---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec
  format: documentation

platforms:
  - name: osx-10.11
    driver_config:
      box: 'jhcook/osx-elcapitan-10.11'

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    attributes:
