# packages.rb attributes

default['workstation']['packages']['homebrew']['taps'] = [
  'caskroom/cask',
  'homebrew/completions',
  'homebrew/dupes'
]

default['workstation']['packages']['homebrew']['pkgs'] = [
  'amazon-ecs-cli',
  'apm-bash-completion',
  'awscli',
  'bash-completion',
  'bash-git-prompt',
  'brew-cask-completion',
  'bundler-completion',
  'coreutils',
  'docker-completion',
  'docker-compose-completion',
  'gem-completion',
  'grep',
  'launchctl-completion',
  'kitchen-completion',
  'macvim',
  'mas',
  'open-completion',
  'packer',
  'packer-completion',
  'pandoc',
  'pip-completion',
  'python',
  'python3',
  'rake-completion',
  'ruby-completion',
  'todo-txt',
  'vagrant-completion',
  'vim'
]

default['workstation']['packages']['homebrew']['casks'] = [
  'atom',
  'box-sync',
  'caffeine',
  'chefdk',
  'daisydisk',
  'docker',
  'dropbox',
  'enpass',
  'flash-player',
  'flux',
  'gimp',
  'google-chrome',
  'google-drive',
  'hermes',
  'inkscape',
  'istat-menus',
  'iterm2',
  'kindle',
  'kitematic',
  'microsoft-office',
  'nosleep',
  'postman',
  'scribus',
  'skype',
  'slack',
  'spectacle',
  'todotxt',
  'utorrent',
  'vagrant',
  'virtualbox',
  'virtualbox-extension-pack',
  'xquartz',
  'yakyak'
]
